### PR TITLE
Fixes for beta 10

### LINKED ISSUE #556: Smaller ui/ux fixes for #531 Separation rewards pairs
Here I will put the not as prioritized fixes for #531

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #556

### CODE REVIEW

**Review by natonnelier — APPROVED** [review]

File: src/components/NumberBadge/index.tsx [hunk 1]
```diff
@@ -6,43 +6,42 @@ export interface NumberBadgeProps {
...
+      border: 1.75px solid rgba(242, 153, 74, 0.65);
       color: #f2994a;
     `}
 
   ${({ badgeTheme }) =>
     badgeTheme === 'red' &&
     css`
       background: rgba(240, 46, 81, 0.08);
-      border: 1px solid rgba(240, 46, 81, 0.65);
+      border: 1.75px solid rgba(240, 46, 81, 0.65);
```
Comment (adamazad) [inline src/components/NumberBadge/index.tsx:44]: The border properties can be broken down and DRY up the code. Alternatively, a hash table can be used to map the colors to their respective CSS properties.

**Review by adamazad — APPROVED** [review]
